/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime false` (hash: fa20c45248179f03546e02233eb4d477)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/worker");
	}
	interface Env {
		ASSETS: Fetcher;
		AI_PROVIDER: string;
		OPENAI_API_KEY: string;
		OPENAI_MODEL: string;
		OPENROUTER_API_KEY: string;
		OPENROUTER_MODEL: string;
		CHAT_TELEMETRY_STDOUT: string;
		R2_PUBLIC_BASE_URL: string;
		R2_PREFIX: string;
		DEMO_PORT: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "AI_PROVIDER" | "OPENAI_API_KEY" | "OPENAI_MODEL" | "OPENROUTER_API_KEY" | "OPENROUTER_MODEL" | "CHAT_TELEMETRY_STDOUT" | "R2_PUBLIC_BASE_URL" | "R2_PREFIX" | "DEMO_PORT">> {}
}
